// File generated by FlutterFire CLI & AI Assistant for project lumo-notification.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qDWQvN8p8iM7u2hgJ84yA97tGrWyn3k',
    appId: '1:385700084800:android:32731c94aad5a7076373a5',
    messagingSenderId: '385700084800',
    projectId: 'lumo-notification',
    storageBucket: 'lumo-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGmkZPx7YGd3rte2yuxNXijhpy26x7eHg',
    appId: '1:385700084800:ios:b5f2b1e4f200e9916373a5',
    messagingSenderId: '385700084800',
    projectId: 'lumo-notification',
    storageBucket: 'lumo-notification.firebasestorage.app',
    iosBundleId: 'com.lumo.pro.pro_app',
  );
}
